'use client';

import React, { useState } from 'react';
import { CLUB_POSTINGS } from '@/lib/data/club';

/**
 * The chit as a journal entry, and the same chit refused.
 *
 * Client component: the site holds which posting is being attempted in state,
 * and the whole point of the set piece is that a visitor can attempt the
 * lopsided one and watch the ledger refuse it. A ledger that accepts an
 * unbalanced entry is a spreadsheet with an audit trail.
 */
export function ClubPosting() {
  const [sel, setSel] = useState(0);
  const p = CLUB_POSTINGS[sel];

  return (
    <>
      <div className="clbtoggle" role="group" aria-label="Choose which posting to attempt">
        {CLUB_POSTINGS.map((post, i) => (
          <button
            type="button"
            className="chip"
            key={post.chip}
            aria-pressed={sel === i}
            onClick={() => setSel(i)}
          >
            {post.chip}
          </button>
        ))}
      </div>

      <div className="clbpost">
        <div className="clbpost__h">
          <span>Journal 8841 · chit PS-4471</span>
          <span>{p.tag}</span>
        </div>

        <div className="clbpost__b">
          <table className="clbjt">
            <caption className="sr">
              The journal entry generated by pro shop chit PS-4471, showing the debit to member
              accounts receivable against the credits to revenue and output tax
            </caption>
            <thead>
              <tr>
                <th scope="col">Account</th>
                <th scope="col" className="n">Debit</th>
                <th scope="col" className="n">Credit</th>
              </tr>
            </thead>
            <tbody>
              {p.rows.map((row) => (
                <tr className={row.side} key={row.account}>
                  <td className="a">{row.account}</td>
                  <td className="n">{row.debit ?? ''}</td>
                  <td className="n">{row.credit ?? ''}</td>
                </tr>
              ))}
            </tbody>
            <tfoot>
              <tr>
                <td className="a">Totals</td>
                <td className="n">{p.debitTotal}</td>
                <td className="n">{p.creditTotal}</td>
              </tr>
            </tfoot>
          </table>
        </div>

        <div className="clbpost__f" aria-live="polite">
          <span className={`clbpost__st clbpost__st--${p.accepted ? 'ok' : 'no'}`}>
            {p.accepted ? 'Posted · balanced' : 'Rejected · unbalanced'}
          </span>
          {p.error && <p className="clbpost__er">{p.error}</p>}
          <p className="small" style={{ marginTop: 'var(--s4)' }}>{p.note}</p>
        </div>
      </div>
    </>
  );
}
